@extends('layouts.master')

@section('pageCSS')
<link rel="stylesheet" href="{{ asset('assets/plugins/select2/select2.min.css') }}">

<style>
 input[readonly] {
  cursor: not-allowed;
 }
</style>

@endsection

@section('content')
<div class="row">
 <div class="col-xl-12">
  <div class="card mb-30">
   <h4 class="font-20 mb-30 mt-30 mx-4">New Customer</h4>
   
   <div class="card-body">
    <form action="{{ url('/workorders/store') }}" method="post">
     @csrf
     <div class="row">
      <div class="col-lg-6 border-right">
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Customer ID</label>
        </div>
        <div class="col-sm-9">
         <input type="text" class="theme-input-style" readonly placeholder="Customer ID will be generated by the system">
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Company</label>
        </div>
        <div class="col-sm-9">
         <select class="search-select" name="company">
          <option value="">Select Company</option>
          
         </select>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold mb-3" for="postal_address">Postal Address</label>
        </div>
        <div class="col-sm-9">
         <textarea id="postal_address" class="theme-input-style style--three" name="postal_address"></textarea>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Postal Code</label>
        </div>
        <div class="col-sm-9">
         <input type="text" class="theme-input-style" name="">
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Extension</label>
        </div>
        <div class="col-sm-9">
         <input type="text" class="theme-input-style" name="">
        </div>
       </div>
       
      </div>
      
      <div class="col-lg-6">
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Billing Address</label>
        </div>
        <div class="col-sm-9">
         <select class="search-select" name="" id="" required>
          <option value="">Select Billing Address</option>
          
         </select>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Country</label>
        </div>
        <div class="col-sm-9">
         <select class="search-select" name="" id="" required>
          <option value="">Select Country</option>
          
         </select>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">Province</label>
        </div>
        <div class="col-sm-9">
         <select class="search-select" name="" id="" required>
          <option value="">Select Province</option>
          
         </select>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold">City</label>
        </div>
        <div class="col-sm-9">
         <select class="search-select" name="" id="" required>
          <option value="">Select City</option>
          
         </select>
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold mb-3">Telephone</label>
        </div>
        <div class="col-sm-9">
         <input type="text" class="theme-input-style" name="">
        </div>
       </div>
       
       <div class="form-row mb-2">
        <div class="col-sm-3">
         <label class="font-14 bold mb-3">Fax</label>
        </div>
        <div class="col-sm-9">
         <input type="text" class="theme-input-style" name="">
        </div>
       </div>
       
      </div>
      
      <div class="col-12">
       <div class="form-row">
        <div class="col-12 text-right pt-3">
         <button type="submit" class="btn long">Save Customer</button>
        </div>
       </div>
      </div>
      
     </div>
    </form>
   </div>
   <hr>
   <div class="card-body pb-0">
    <div class="d-flex justify-content-between align-items-center">
     <div class="title-content">
      <h4 class="mb-2">New Contacts</h4>
     </div>
     <div>
      <a href="" type="button" class="btn btn-secondary px-3 py-2">Add Contact</a>
     </div>
    </div>
   </div>
   <div class="table-responsive">
    <table class="invoice-list" id="contacts_table">
     <thead>
      <tr>
       <th>SR#</th>
       <th>Contact Title</th>
       <th>First Name</th>
       <th>Last Name</th>
       <th>Direct</th>
       <th>Cell</th>
       <th>Email</th>
       <th>Notes</th>
       <th>Actions</th>
      </tr>
     </thead>
     <tbody>
      <tr><td colspan="9" class="text-center"><p>No Data Found!</p></td></tr>
     </tbody>
    </table>
   </div>
   
  </div>
  
 </div>
 
</div>

</div>
</div>


@endsection

@section('pageScript')

<script src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>



<script>
 $(document).ready(function() {
  
  $(".search-select").select2({
   dropdownAutoWidth: false,
   width: '100%'
  });
  
  $(function () {
   
   var table = $('#contacts_table').DataTable({
    processing: true,
    serverSide: true,
    paging: true,
    pageLength: 10,
    ajax: "{{ route('contacts.list') }}",
    columns: [
    {data: 'DT_RowIndex', name: 'DT_RowIndex', orderable: false, searchable: false},
    {data: 'company_name', name: 'company.name'},
    {data: 'billing_address_name', name: 'billing_address.name'},
    {data: 'postal_address', name: 'customer_parent.postal_address'},
    {data: 'city', name: 'customer_parent.city'},
    {data: 'contacts_persons', name: 'contacts_persons', searchable: true},
    {
     data: 'action', 
     name: 'action', 
     orderable: false, 
     searchable: false
    },
    ]
   });
   
  });
  
  
  $('#wo_company_id').change(function() {
   var url = "{{url('/get-company-addresses')}}";
   $.ajax({
    type:'GET',
    url: url,
    data: {
     wo_company_id: $(this).val(),
    },
    success:function(data) {
     $('#wo_billing_address').empty();
     $('#wo_contact_person').empty();
     
     var defaultOption1 = new Option('Select Billing Address', '', false, false);
     $('#wo_billing_address').append(defaultOption1).trigger('change');
     
     var defaultOption2 = new Option('Select Contact Person', '', false, false);
     $('#wo_contact_person').append(defaultOption2).trigger('change');
     
     $(data.response).each(function(i) {
      var newOption = new Option(data.response[i]['name'], data.response[i]['billing_address_id'], false, false);
      $('#wo_billing_address').append(newOption).trigger('change');
     });
    }
   });
  });
  
  $('#wo_billing_address').change(function() {
   if($(this).val() != '') {
    var url = "{{url('/get-company-persons')}}";
    $.ajax({
     type:'GET',
     url: url,
     data: {
      wo_company_id: $('#wo_company_id').val(),
      wo_billing_address_id: $(this).val(),
     },
     success:function(data) {
      $('#wo_contact_person').empty();
      var defaultOption = new Option('Select Contact Person', '', false, false);
      $('#wo_contact_person').append(defaultOption).trigger('change');
      $(data.response).each(function(i) {
       var newOption = new Option(
       ((data.response[i]['first_name']) == null || (data.response[i]['first_name']) == '' ? '' : data.response[i]['first_name'])+' '+((data.response[i]['last_name']) == null || (data.response[i]['last_name']) == '' ? '' : data.response[i]['last_name']), 
       data.response[i]['child_id'], 
       false, 
       false
       );
       $('#wo_contact_person').append(newOption).trigger('change');
      });
      $('#postal_address').text(data[0].postal_address);
     }
    });
   }
  });
  
 });
</script>
@endsection