@extends('layouts.master')

@section('pageCSS')
<link rel="stylesheet" href="{{ asset('assets/plugins/datepicker/datepicker.min.css') }}">
<link rel="stylesheet" href="{{ asset('assets/plugins/select2/select2.min.css') }}">
<link href="{{ asset('assets/plugins/jquery-smartwizard/smart_wizard_all.min.css') }}" rel="stylesheet" type="text/css" />
<link rel="stylesheet" href="{{ asset('assets/plugins/dropzone/dropzone.min.css') }}">

<style>
 .main-content #smartwizard .nav li a {
  height: 50px;
 }
 .sw-theme-arrows>.nav .nav-link {
  color: #aeaeae;
  border-color: #f8f8f8;
  background: #fafafa;
  background: -moz-linear-gradient(left,#fafafa 0,#dbf7e8 100%);
  background: -webkit-linear-gradient(left,#fafafa 0,#dbf7e8 100%);
  background: linear-gradient(to right,#fafafa 0,#dbf7e8 100%);
  /* cursor: not-allowed; */
 }
 input[readonly] {
  cursor: not-allowed;
 }
</style>

@endsection

@section('content')
<div class="row">
 <div class="col-xl-12">
  <div class="card mb-30">
   <h4 class="font-20 mb-30 mt-30 mx-4">New Workorder</h4>
   
      <div class="card-body">
       <form action="{{ url('/workorders/store') }}" method="post">
        @csrf
        <div class="row">
         <div class="col-lg-6 border-right">
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Workorder ID</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly placeholder="Workorder ID will be generated by the system">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold" for="billing_add">Billing Address</label>
           </div>
           <div class="col-sm-9">
            <select class="search-select" name="billing_address" id="wo_billing_address" required>
             <option value="">Select Billing Address</option>
            </select>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Order Date</label>
           </div>
           <div class="col-sm-9">
            <!-- Date Picker -->
            <div class="dashboard-date style--four">
             <span class="input-group-addon">
              <img src="{{ asset('assets/img/svg/calender.svg') }}" alt="" class="svg">
             </span>
             <input type="text" class="simple-date-picker" placeholder="Select Date" name="date_received" autocomplete="off"/>
            </div>
            <!-- End Date Picker -->
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">PO#</label>
           </div>
           <div class="col-sm-9">
            <input type="number" class="theme-input-style" name="po_num">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Reference#</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" name="reference_num">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Branch</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" name="branch">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Country</label>
           </div>
           <div class="col-sm-9">
            <select class="search-select" name="country">
             <option value="">Select Country</option>
             @if (isset($countries))
             @foreach ($countries as $country)
             <option value="{{ $country->name }}">
              {{ $country->name }}
             </option>
             @endforeach
             @endif
            </select>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">SECP# (If Any)</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" name="serial_num">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold" for="address">Address</label>
           </div>
           <div class="col-sm-9">
            <textarea id="address" class="theme-input-style style--three" name="problem_desc"></textarea>
           </div>
          </div>
          
          <div class="form-row mb-2"> 
           <div class="col-sm-3">
            <label class="font-14 bold">Deliver Date</label>
           </div>
           <div class="col-sm-9">
            <!-- Date Picker -->
            <div class="dashboard-date style--four">
             <span class="input-group-addon">
              <img src="{{ asset('assets/img/svg/calender.svg') }}" alt="" class="svg">
             </span>
             <input type="text" class="simple-date-picker" placeholder="Select Date" name="date_delivered" autocomplete="off"/>
            </div>
            <!-- End Date Picker -->
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Amount Due</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-9 offset-sm-3">
            <div class="d-flex align-items-center">
             <label class="custom-checkbox position-relative mr-2">
              <input type="checkbox" id="hard_copy" name="hardcopy_delivered">
              <span class="checkmark"></span>
             </label>
             <label for="hard_copy">Hard Copy Delivered</label>
            </div>
           </div>
          </div>
          
         </div>
         
         <div class="col-lg-6">
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold">Company</label>
           </div>
           <div class="col-sm-9">
            <select class="search-select" name="company_id" id="wo_company_id" required>
             <option value="">Select Company</option>
             @if (isset($company))
             @foreach ($company as $com)
             <option value="{{ $com->company_id }}">
              {{ $com->name }}
             </option>
             @endforeach
             @endif
            </select>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Contact Person</label>
           </div>
           <div class="col-sm-9">
            <select class="search-select" name="contact_person" id="wo_contact_person">
             <option value="">Select Contact Person</option>
            </select>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3" for="postal_address">Postal Address</label>
           </div>
           <div class="col-sm-9">
            <textarea id="postal_address" class="theme-input-style style--three" name="postal_address"></textarea>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Report Name</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" name="report_name">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Vendor</label>
           </div>
           <div class="col-sm-9">
            <select class="search-select" name="vendor_id" required>
             <option value="">Select Vendor</option>
             @if (isset($vendor))
             @foreach ($vendor as $ven)
             <option value="{{ $ven->vendor_id }}">
              {{ $ven->name }}
             </option>
             @endforeach
             @endif
            </select>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Subtotal</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Discount %</label>
           </div>
           <div class="col-sm-9">
            <input type="number" class="theme-input-style" name="discount">
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-9 offset-sm-3">
            <div class="d-flex align-items-center">
             <label class="custom-checkbox position-relative mr-2">
              <input type="checkbox" id="taxable_invoice" name="taxable">
              <span class="checkmark"></span>
             </label>
             <label for="taxable_invoice">Taxable Invoice</label>
            </div>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Sales Tax %</label>
           </div>
           <div class="col-sm-9">
            <input type="number" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Sales Tax</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Order Total</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2">
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Payments</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" readonly>
           </div>
          </div>
          
          <div class="form-row mb-2"> 
           <div class="col-sm-3">
            <label class="font-14 bold mb-3">Financial</label>
           </div>
           <div class="col-sm-9">
            <input type="text" class="theme-input-style" name="financial">
           </div>
          </div>
          
         </div>
         
         <div class="col-12">
          <div class="form-row">
           <div class="col-12 text-right py-3">
            <button type="submit" class="btn long">Save</button>
           </div>
          </div>
         </div>
         
        </div>
       </form>
      </div>
     
    </div>
    
   </div>
   
  </div>
  
 </div>
</div>


@endsection

@section('pageScript')
<script src="{{ asset('assets/plugins/datepicker/datepicker.min.js') }}"></script>
<script src="{{ asset('assets/plugins/datepicker/i18n/datepicker.en.js') }}"></script>

<script src="{{ asset('assets/plugins/select2/select2.min.js') }}"></script>



<script>
 $(document).ready(function() {
  
  $('.simple-date-picker').datepicker({
   language: 'en',
   dateFormat: 'dd-mm-yyyy',
  });
  
  $(".search-select").select2({
   dropdownAutoWidth: false,
   width: '100%'
  });
  $(".search-select-w-100").select2({
   dropdownAutoWidth: false,
   width: '100%',
  });
  
  $('#wo_company_id').change(function() {
   var url = "{{url('/get-company-addresses')}}";
   $.ajax({
    type:'GET',
    url: url,
    data: {
     wo_company_id: $(this).val(),
    },
    success:function(data) {
     $('#wo_billing_address').empty();
     $('#wo_contact_person').empty();
     
     var defaultOption1 = new Option('Select Billing Address', '', false, false);
     $('#wo_billing_address').append(defaultOption1).trigger('change');
     
     var defaultOption2 = new Option('Select Contact Person', '', false, false);
     $('#wo_contact_person').append(defaultOption2).trigger('change');
     
     $(data.response).each(function(i) {
      var newOption = new Option(data.response[i]['name'], data.response[i]['billing_address_id'], false, false);
      $('#wo_billing_address').append(newOption).trigger('change');
     });
    }
   });
  });
  
  $('#wo_billing_address').change(function() {
   if($(this).val() != '') {
    var url = "{{url('/get-company-persons')}}";
    $.ajax({
     type:'GET',
     url: url,
     data: {
      wo_company_id: $('#wo_company_id').val(),
      wo_billing_address_id: $(this).val(),
     },
     success:function(data) {
      $('#wo_contact_person').empty();
      var defaultOption = new Option('Select Contact Person', '', false, false);
      $('#wo_contact_person').append(defaultOption).trigger('change');
      $(data.response).each(function(i) {
       var newOption = new Option(
       ((data.response[i]['first_name']) == null || (data.response[i]['first_name']) == '' ? '' : data.response[i]['first_name'])+' '+((data.response[i]['last_name']) == null || (data.response[i]['last_name']) == '' ? '' : data.response[i]['last_name']), 
       data.response[i]['child_id'], 
       false, 
       false
       );
       $('#wo_contact_person').append(newOption).trigger('change');
      });
      $('#postal_address').text(data[0].postal_address);
     }
    });
   }
  });
  
 });
</script>
@endsection